location = /gym { return 308 /gym/; }
location = /gym/program { alias /var/www/gym/index.html; }
location = /gym/program/ { alias /var/www/gym/index.html; }
location /gym/ { alias /var/www/gym/; index index.html; }
