location = /gym { return 308 /gym/; }
location = /gym/program { root /var/www; default_type text/html; try_files /gym/index.html =404; }
location = /gym/program/ { return 308 /gym/program; }
location /gym/ { alias /var/www/gym/; index index.html; }
